from __future__ import annotations

import sys
from datetime import date, timedelta


sys.path.insert(0, "backend")

from app.models.api import TaskInput
from app.storage.sqlite import SqliteTaskStore


def build_tasks() -> list[TaskInput]:
    base_date = date(2026, 3, 30)
    raw_tasks = [
        {
            "id": "task-001",
            "title": "VCc02: Telegram-бот модерации",
            "description": "Продакшен-ориентированный Telegram-бот модерации на aiogram с PostgreSQL, Docker и web-панелью управления.",
            "project": "VCc02",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/VCc02",
            "type": "development",
            "deadline": (base_date + timedelta(days=1)).isoformat(),
            "estimated_hours": 8,
            "importance": "critical",
            "status": "todo",
            "archived": False,
            "tags": ["telegram", "aiogram", "postgresql", "docker", "panel"],
            "dependencies": [],
            "notes": "Один из самых сильных репозиториев профиля: есть модерация, логирование, Docker-развертывание и панель управления.",
        },
        {
            "id": "task-002",
            "title": "Vcc01: бот-опросник с PostgreSQL и backup в SQLite",
            "description": "Telegram-бот для сбора анкет пользователей с основной записью в PostgreSQL, локальным backup в SQLite и экспортом в Excel.",
            "project": "Vcc01",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/Vcc01",
            "type": "development",
            "deadline": (base_date + timedelta(days=2)).isoformat(),
            "estimated_hours": 7,
            "importance": "critical",
            "status": "todo",
            "archived": False,
            "tags": ["telegram", "postgresql", "sqlite", "excel", "python"],
            "dependencies": [],
            "notes": "Интересен сочетанием основной БД, резервного хранения и выгрузки отчетов в одном рабочем процессе.",
        },
        {
            "id": "task-003",
            "title": "lessonPErr4.4: коллекция AI Assistant Projects",
            "description": "Репозиторий с двумя AI-проектами: Telegram-ботом для лидов и Flask-приложением с AI-чат-виджетом и сохранением в Google Sheets.",
            "project": "lessonPErr4.4",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/lessonPErr4.4",
            "type": "development",
            "deadline": (base_date + timedelta(days=3)).isoformat(),
            "estimated_hours": 8,
            "importance": "critical",
            "status": "todo",
            "archived": False,
            "tags": ["openai", "telegram", "flask", "google-sheets", "ai-assistant"],
            "dependencies": [],
            "notes": "Широкий showcase-репозиторий, потому что объединяет web и bot интерфейсы вокруг AI-диалога и заявок.",
        },
        {
            "id": "task-004",
            "title": "Crew_Ai_Example: мультиагентный маркетинговый пайплайн",
            "description": "Пример на CrewAI, который строит маркетинговый план с ролями researcher, writer, reviewer и translator.",
            "project": "Crew_Ai_Example",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/Crew_Ai_Example",
            "type": "management",
            "deadline": (base_date + timedelta(days=4)).isoformat(),
            "estimated_hours": 6,
            "importance": "critical",
            "status": "todo",
            "archived": False,
            "tags": ["crewai", "openai", "agents", "marketing", "automation"],
            "dependencies": [],
            "notes": "Один из самых современных репозиториев в профиле: хорошо показывает оркестрацию нескольких AI-агентов.",
        },
        {
            "id": "task-005",
            "title": "OG01: Telegram-бот планировщик задач",
            "description": "Учебный Telegram-бот-планировщик, который собирает события по времени и строит расписание через диалог.",
            "project": "OG01",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/OG01",
            "type": "development",
            "deadline": (base_date + timedelta(days=5)).isoformat(),
            "estimated_hours": 5,
            "importance": "high",
            "status": "todo",
            "archived": False,
            "tags": ["telegram", "planner", "scheduler", "bot"],
            "dependencies": [],
            "notes": "Выделен как практический bot-сценарий с понятным пользовательским потоком, а не как пустая учебная заготовка.",
        },
        {
            "id": "task-006",
            "title": "ordersystem: тренировка командной разработки",
            "description": "Репозиторий для отработки командной разработки вокруг идеи order system.",
            "project": "ordersystem",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/ordersystem",
            "type": "management",
            "deadline": (base_date + timedelta(days=6)).isoformat(),
            "estimated_hours": 4,
            "importance": "high",
            "status": "todo",
            "archived": False,
            "tags": ["teamwork", "architecture", "backend"],
            "dependencies": [],
            "notes": "README короткий, но репозиторий выделяется как база для совместной разработки и архитектурной практики.",
        },
        {
            "id": "task-007",
            "title": "DJ02: приложение и работа с моделями",
            "description": "Репозиторий по созданию приложения с фокусом на модели данных и структурированную backend-логику.",
            "project": "DJ02",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/DJ02",
            "type": "development",
            "deadline": (base_date + timedelta(days=7)).isoformat(),
            "estimated_hours": 4,
            "importance": "high",
            "status": "todo",
            "archived": False,
            "tags": ["django", "models", "backend", "python"],
            "dependencies": [],
            "notes": "Полезен как model-centric репозиторий, где важна работа со структурой предметной области.",
        },
        {
            "id": "task-008",
            "title": "TG06: разработка чат-бота",
            "description": "Компактный репозиторий по разработке чат-бота, полезный для сравнения с более крупными Telegram-проектами.",
            "project": "TG06",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/TG06",
            "type": "development",
            "deadline": (base_date + timedelta(days=8)).isoformat(),
            "estimated_hours": 4,
            "importance": "high",
            "status": "todo",
            "archived": False,
            "tags": ["chatbot", "telegram", "python"],
            "dependencies": [],
            "notes": "Добавлен как более легкий bot-кейс рядом с более зрелыми Telegram-репозиториями.",
        },
        {
            "id": "task-009",
            "title": "AZ03: визуализация данных на Matplotlib",
            "description": "Проект по созданию диаграмм и графиков на Matplotlib; хороший пример визуальной аналитики.",
            "project": "AZ03",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/AZ03",
            "type": "analytics",
            "deadline": (base_date + timedelta(days=9)).isoformat(),
            "estimated_hours": 3,
            "importance": "high",
            "status": "todo",
            "archived": False,
            "tags": ["matplotlib", "analytics", "data-viz", "python"],
            "dependencies": [],
            "notes": "Добавляет в подборку отдельное направление data visualization, а не только web и bots.",
        },
        {
            "id": "task-010",
            "title": "AZ01: основы NumPy и Pandas",
            "description": "Репозиторий про базовые инструменты анализа данных на Python: NumPy и Pandas.",
            "project": "AZ01",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/AZ01",
            "type": "analytics",
            "deadline": (base_date + timedelta(days=10)).isoformat(),
            "estimated_hours": 3,
            "importance": "medium",
            "status": "todo",
            "archived": False,
            "tags": ["numpy", "pandas", "data", "python"],
            "dependencies": [],
            "notes": "Отобран как фундаментальный data-stack репозиторий, расширяющий профиль автора за пределы ботов.",
        },
        {
            "id": "task-011",
            "title": "PS03: парсинг HTML через BeautifulSoup",
            "description": "Практика web scraping для разбора HTML-контента с помощью BeautifulSoup.",
            "project": "PS03",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/PS03",
            "type": "analytics",
            "deadline": (base_date + timedelta(days=11)).isoformat(),
            "estimated_hours": 3,
            "importance": "medium",
            "status": "todo",
            "archived": False,
            "tags": ["beautifulsoup", "web-scraping", "html", "python"],
            "dependencies": [],
            "notes": "Практичный scraping-репозиторий и хороший представитель направления автоматизированного сбора данных.",
        },
        {
            "id": "task-012",
            "title": "PS02: основы Requests",
            "description": "Учебный проект по HTTP-запросам и библиотеке Requests как базе для API и scraping-сценариев.",
            "project": "PS02",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/PS02",
            "type": "analytics",
            "deadline": (base_date + timedelta(days=12)).isoformat(),
            "estimated_hours": 2,
            "importance": "medium",
            "status": "todo",
            "archived": False,
            "tags": ["requests", "http", "api", "python"],
            "dependencies": [],
            "notes": "Небольшой, но важный building block для интеграций, scraping и работы с внешними сервисами.",
        },
        {
            "id": "task-013",
            "title": "PS01: введение в web parsing",
            "description": "Вводный репозиторий по web parsing, который служит стартовой точкой для линейки PS.",
            "project": "PS01",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/PS01",
            "type": "analytics",
            "deadline": (base_date + timedelta(days=13)).isoformat(),
            "estimated_hours": 2,
            "importance": "medium",
            "status": "todo",
            "archived": False,
            "tags": ["web-scraping", "intro", "python"],
            "dependencies": [],
            "notes": "Оставлен в базе как часть логичной прогрессии PS01 -> PS02 -> PS03.",
        },
        {
            "id": "task-014",
            "title": "OG03: браузерная игра-тир",
            "description": "Небольшая браузерная игра, где нужно попадать мышкой по движущейся мишени.",
            "project": "OG03",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/OG03",
            "type": "design",
            "deadline": (base_date + timedelta(days=14)).isoformat(),
            "estimated_hours": 3,
            "importance": "medium",
            "status": "todo",
            "archived": False,
            "tags": ["frontend", "game", "interaction", "javascript"],
            "dependencies": [],
            "notes": "Выбран как более живой интерактивный проект, который добавляет разнообразие к подборке учебных репозиториев.",
        },
        {
            "id": "task-015",
            "title": "OB05: практика с PyGame",
            "description": "Репозиторий по изучению PyGame и event-driven подхода в Python-разработке игр.",
            "project": "OB05",
            "client": "HoDzha",
            "github_url": "https://github.com/HoDzha/OB05",
            "type": "development",
            "deadline": (base_date + timedelta(days=15)).isoformat(),
            "estimated_hours": 3,
            "importance": "medium",
            "status": "todo",
            "archived": False,
            "tags": ["pygame", "game-dev", "python"],
            "dependencies": [],
            "notes": "Закрывает подборку игровым Python-кейсом и показывает техническое разнообразие профиля.",
        },
    ]
    return [TaskInput.model_validate(item) for item in raw_tasks]


def main() -> None:
    store = SqliteTaskStore("sqlite:///./data/freelance_flow.db")
    store.replace_tasks(build_tasks())
    print(f"TOTAL {len(store.list_tasks())}")
    for task in store.list_tasks()[:3]:
        print(task.id, task.title.encode('unicode_escape').decode('ascii'))


if __name__ == "__main__":
    main()
